version: "3.7"
services:
  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
  eventstore-db:
    image: eventstore/eventstore:20.10.0-bionic
    ports:
      - 2113:2113
      - 1113:1113
    command: --insecure --run-projections=All --enable-atom-pub-over-http
  active-games-projection:
    build:
      context: .
      dockerfile: src/active-games-projection/Dockerfile
    image: tb-active-games-projection
    environment:
      - EVENTSTOREDB_ENDPOINT=eventstore-db:2113
      - RABBITMQ_ENDPOINT=amqp://rabbit:5672
  