version: "3.7"
services:
  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
  eventstore-db:
    image: eventstore/eventstore:20.10.0-bionic
    ports:
      - 2113:2113
      - 1113:1113
    command: --insecure --run-projections=All --enable-atom-pub-over-http
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: tb-build
  active-games-projection:
    build:
      context: .
      dockerfile: src/active-games-projection/Dockerfile
    image: tb-active-games-projection
    command: "./wait-for-it.sh rabbit:5672 -t 0 -- node out/index.js"
    env_file: src/.env
    environment:
      - EVENTSTOREDB_ENDPOINT=eventstore-db:2113
      - RABBITMQ_ENDPOINT=amqp://rabbit:5672
  game-projection:
    build:
      context: .
      dockerfile: src/game-projection/Dockerfile
    image: tb-game-projection
    command: "./wait-for-it.sh rabbit:5672 -t 0 -- node out/index.js"
    env_file: src/.env
    environment:
      - EVENTSTOREDB_ENDPOINT=eventstore-db:2113
      - RABBITMQ_ENDPOINT=amqp://rabbit:5672
  game-logic:
    build:
      context: .
      dockerfile: src/gamelogic/Dockerfile
    image: tb-game-logic
    command: "./wait-for-it.sh rabbit:5672 -t 0 -- node out/index.js"
    env_file: src/.env
    environment:
      - EVENTSTOREDB_ENDPOINT=eventstore-db:2113
      - RABBITMQ_ENDPOINT=amqp://rabbit:5672
  rtm:
    build:
      context: .
      dockerfile: src/rtm/Dockerfile
    image: tb-rtm
    command: "./wait-for-it.sh rabbit:5672 -t 0 -- node out/index.js"
    env_file: src/.env
    environment:
      - EVENTSTOREDB_ENDPOINT=eventstore-db:2113
      - RABBITMQ_ENDPOINT=amqp://rabbit:5672